// Faz G + Bursluluk 2.0 (0021): yönetici sınav, seans ve seans × sınıf kontenjanı tanımlar; girişsiz başvuru (seans seçerek, takip kodu);
// başvuran kodla görüntüler ve süre içinde düzenler; yönetici başvuruyu işler (onay, salon, Excel, okul öğrencisi).
import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { loginAdmin, logout, resetAdminMfa, service, shot } from './helpers'

async function axe(page: Page, label: string) {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.waitForTimeout(300)
  const r = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()
  const bad = r.violations.filter((v) => v.impact === 'serious' || v.impact === 'critical')
  expect(bad.map((v) => `${label}: ${v.id} (${v.nodes.length}) ${v.nodes[0]?.target}`)).toEqual([])
}
const svc = service()
const day = (n: number) => new Date(Date.now() + 3 * 3600_000 + n * 86400_000).toISOString().slice(0, 10)
const NAME = `E2E Bursluluk ${Date.now() % 100000}`
const inApp = (page: Page) => expect(page.getByRole('navigation', { name: 'Ana menü' })).toBeVisible()

test.describe.serial('Bursluluk', () => {
  let secret = ''
  test.beforeAll(async () => {
    await svc.from('scholarship_exams').delete().like('name', 'E2E %')
    await svc.from('school_settings').delete().or('key.eq.modul.bursluluk,key.like.bursluluk.%')
    await resetAdminMfa()
  })
  test.afterAll(async () => {
    await svc.from('scholarship_exams').delete().like('name', 'E2E %')
    await svc.from('school_settings').delete().or('key.eq.modul.bursluluk,key.like.bursluluk.%')
  })

  test('modül kapalıyken başvuru sayfası boş; yönetici modülü açar ve sınav oluşturur', async ({ page }) => {
    await page.goto('/bursluluk')
    await expect(page.getByText('Şu anda başvuruya açık bursluluk sınavı yok.')).toBeVisible()
    secret = await loginAdmin(page)
    await inApp(page)
    await page.goto('/yonetim?sekme=moduller')
    await page.getByRole('switch', { name: 'Bursluluk modülü' }).click()
    await expect(page.getByRole('switch', { name: 'Bursluluk modülü' })).toHaveAttribute('aria-checked', 'true')
    await page.goto('/yonetim?sekme=bursluluk')
    await page.getByRole('button', { name: 'Bursluluk sınavı oluştur' }).click()
    const dlg = page.getByRole('dialog', { name: 'Bursluluk sınavı oluştur' })
    await dlg.getByLabel('Sınav adı').fill(NAME)
    await dlg.getByLabel('Sınav tarihi (ilk gün)').fill(day(20))
    await dlg.getByLabel('Genel üst sınır (isteğe bağlı)').fill('10')
    await dlg.getByLabel('Başvuru başlangıcı').fill(day(0))
    await dlg.getByLabel('Son başvuru').fill(day(10))
    await dlg.getByRole('group', { name: 'Sınıf seviyeleri' }).getByRole('button', { name: '5', exact: true }).click()
    await dlg.getByRole('group', { name: 'Sınıf seviyeleri' }).getByRole('button', { name: '8', exact: true }).click()
    await dlg.getByLabel('Sınav yeri (isteğe bağlı)').fill('Ana bina')
    await dlg.getByRole('switch', { name: /Başvuran başvurusunu düzenleyebilir/ }).click()
    await dlg.getByRole('button', { name: 'Sınavdan 10 gün önce' }).click()
    await expect(dlg.getByLabel('Düzenleme son tarihi')).toHaveValue(day(10))
    await dlg.getByRole('button', { name: 'Kaydet' }).click()
    await expect(page.getByText('Başvuru 0 / 10 (genel üst sınır)')).toBeVisible()
    // Seans ve seans × sınıf kontenjanı
    const ses = page.getByRole('region', { name: 'Seanslar ve kontenjan' })
    await expect(ses).toContainText('Bu sınav için henüz seans tanımlanmamış')
    await ses.getByRole('button', { name: 'Seans ekle' }).click()
    const sd = page.getByRole('dialog', { name: 'Seans ekle' })
    await expect(sd.getByLabel('Sınav günü')).toHaveValue(day(20))
    await sd.getByLabel('Seans adı (isteğe bağlı)').fill('Sabah')
    await sd.getByRole('button', { name: 'Kaydet' }).click()
    const srow = ses.getByTestId('session-row')
    await srow.getByLabel(/5\. sınıf kontenjan$/).fill('2')
    await srow.getByLabel(/8\. sınıf kontenjan$/).fill('1')
    await srow.getByRole('button', { name: 'Kaydet' }).click()
    await expect(page.getByText('Kontenjan kaydedildi')).toBeVisible()
    await expect(srow).toContainText('0 başvuru · kalan 2')
    await axe(page, 'bursluluk yönetimi')
  })

  test('girişsiz başvuru (telefonda): seans seçimi, takip kodu, başvurumu görüntüle ve düzenle', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 })
    await page.goto('/bursluluk')
    await expect(page.getByRole('heading', { name: 'Bursluluk sınavı', exact: true })).toBeVisible()
    await page.getByRole('group', { name: 'Sınıf seviyesi' }).getByRole('button', { name: '5. sınıf' }).click()
    const card = page.getByRole('group', { name: 'Seanslar' }).getByRole('button', { name: /Sabah/ })
    await expect(card).toContainText('10:00 – 12:30')
    await expect(card).toContainText('2 kişilik yer kaldı')
    await card.click()
    await page.getByLabel('Öğrencinin adı soyadı').fill('Mina Çelik')
    await page.getByLabel('Okulu (isteğe bağlı)').fill('Cumhuriyet İlkokulu')
    await page.getByLabel('Velinin adı soyadı').fill('Serkan Çelik')
    await page.getByLabel('Telefon').fill('0532 444 55 66')
    await page.getByRole('button', { name: 'Başvuruyu tamamla' }).click()
    await expect(page.getByRole('alert')).toHaveText('Aydınlatma metnini okuduğunuzu ve bilgi edindiğinizi belirtin.')
    await axe(page, 'başvuru formu')
    await page.getByRole('checkbox', { name: /Aydınlatma metnini okudum/ }).click()
    await page.getByRole('button', { name: 'Başvuruyu tamamla' }).click()
    const done = page.getByRole('region', { name: 'Başvuru alındı' })
    await expect(done).toContainText('Mina Çelik')
    await expect(done).toContainText('10:00 – 12:30 · Sabah')
    await expect(page.getByTestId('tracking-code')).toHaveText(/^BK-[A-Z2-9]{4}-[A-Z2-9]{4}$/)
    const code = (await page.getByTestId('tracking-code').textContent())!
    await axe(page, 'başvuru alındı')
    await shot(page, 'g1-bursluluk-basvuru', false)

    // Başvurumu görüntüle → düzenle (telefon)
    await done.getByRole('button', { name: 'Başvurumu görüntüle' }).click()
    await page.getByRole('button', { name: 'Görüntüle', exact: true }).click()
    const box = page.getByRole('region', { name: 'Başvuru' })
    await expect(box).toContainText(code)
    await expect(box).toContainText('Değerlendiriliyor')
    await expect(box).toContainText('05** *** ** 66')
    await axe(page, 'başvuru takip')
    await box.getByRole('button', { name: 'Başvuruyu düzenle' }).click()
    const form = page.getByRole('form', { name: 'Başvuruyu düzenle' })
    await form.getByLabel('Yeni telefon (boş = değişmez)').fill('0532 555 66 77')
    await form.getByRole('button', { name: 'Değişiklikleri kaydet' }).click()
    await expect(box).toContainText('05** *** ** 77')
    await shot(page, 'g1b-bursluluk-takip', false)

    // Yanlış kod: genel hata
    await page.getByLabel('Takip kodu').fill('BK-AAAA-AAAA')
    await page.getByRole('button', { name: 'Görüntüle', exact: true }).click()
    await expect(page.getByRole('alert')).toHaveText('Başvuru bulunamadı.')
  })

  test('yönetici başvuruyu işler: salon/saat, onay, süzme, Excel, okul öğrencisi', async ({ page }) => {
    await loginAdmin(page, secret)
    await inApp(page)
    await page.goto('/yonetim?sekme=bursluluk')
    const row = page.getByTestId('application-row').filter({ hasText: 'Mina Çelik' })
    await expect(row).toContainText('Bekliyor')
    await expect(row.getByLabel('Mina Çelik seans')).toHaveValue(/.+/)
    await row.getByLabel('Mina Çelik salon').fill('A-3')
    await row.getByRole('button', { name: 'Kaydet' }).click()
    await expect(page.getByText('Mina Çelik: salon kaydedildi')).toBeVisible()
    await row.getByRole('button', { name: 'Mina Çelik onayla' }).click()
    await expect(row).toContainText('Onaylandı')
    await page.getByLabel('Okul öğrencisinden başvuru oluştur').selectOption({ label: 'Elif Yıldız · 8/A' })
    await page.getByLabel('Başvurunun seansı').selectOption({ index: 1 })
    await page.getByRole('button', { name: 'Ekle', exact: true }).click()
    await expect(page.getByTestId('application-row').filter({ hasText: 'Elif Yıldız' })).toContainText('okul öğrencisi')
    await page.getByLabel('Sınıf seviyesi').selectOption('5')
    await expect(page.getByTestId('application-row')).toHaveCount(1)
    const dl = page.waitForEvent('download')
    await page.getByRole('button', { name: /Excel'e aktar \(1\)/ }).click()
    const file = await dl
    expect(file.suggestedFilename()).toMatch(/^bursluluk-e2e-bursluluk-\d+\.csv$/)
    const csv = (await (await file.createReadStream()).toArray()).map(String).join('')
    const gun = new Date(day(20)).toLocaleDateString('tr-TR')
    expect(csv).toMatch(new RegExp(`BK-[A-Z2-9]{4}-[A-Z2-9]{4};Mina Çelik;5\\. sınıf;Cumhuriyet İlkokulu;Serkan Çelik;0532 555 66 77;;${gun.replace(/\./g, '\\.')};Sabah;10:00–12:30;A-3;Onaylandı`))
    await axe(page, 'başvurular')
    await shot(page, 'g2-bursluluk-basvurular')
    await logout(page)
  })
})
