// Yönetim Merkezi genişletme (0024): arama, sınıf aktif/pasif, öğrenci arşivi, öğretmen ders ataması, onaylar,
// "öğretmenler ödev verebilir", yönetici Bugün düzeni ve kart genişliği, duyuru listesi, güvenlik özeti, mobil görünüm.
import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { DEMO, login, loginAdmin, logout, resetAdminMfa, service } from './helpers'

async function axe(page: Page, label: string) {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.waitForTimeout(300)
  const r = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()
  const bad = r.violations.filter((v) => v.impact === 'serious' || v.impact === 'critical')
  expect(bad.map((v) => `${label}: ${v.id} (${v.nodes.length}) ${v.nodes[0]?.target}`)).toEqual([])
}
const menuGroup = (page: Page) => page.getByRole('group', { name: 'Yönetim bölümü' })
const svc = service()
const STU = 'Arşiv Denemesi'
const ANN = 'Yönetim listesinden silinecek duyuru'

test.describe.serial('Yönetim Merkezi genişletme', () => {
  let secret = ''
  const clean = async () => {
    await svc.from('students').delete().eq('full_name', STU)
    await svc.from('announcements').delete().eq('title', ANN)
    await svc.from('classes').update({ active: true }).eq('name', '6/A')
    await svc.from('school_settings').delete().in('key', ['odev.ogretmen_verebilir', 'panel.yonetim', 'panel.veli'])
    const { data: fen } = await svc.from('profiles').select('id').eq('email', 'fen@buluskure.k12.tr').single()
    const { data: c7 } = await svc.from('classes').select('id').eq('name', '8/C').single()
    if (fen && c7) await svc.from('teaching_assignments').delete().eq('teacher_id', fen.id).eq('class_id', c7.id)
  }
  test.beforeAll(async () => {
    await resetAdminMfa()
    await clean()
  })
  test.afterAll(clean)

  test('arama bölümleri süzer; yeni bölümler ve güvenlik özeti', async ({ page }) => {
    secret = await loginAdmin(page)
    await page.goto('/yonetim')
    await page.getByLabel('Yönetimde ara').fill('arşiv')
    await expect(menuGroup(page).getByRole('button')).toHaveText(['Öğrenciler'])
    await page.getByLabel('Yönetimde ara').fill('dashboard')
    await expect(menuGroup(page).getByRole('button')).toHaveText(['Ana sayfa düzeni'])
    await page.getByLabel('Yönetimde ara').fill('xyzxyz')
    await expect(page.getByText('Eşleşen bölüm yok.')).toBeVisible()
    await page.getByLabel('Yönetimde ara').fill('')
    for (const n of ['Mesajlaşma', 'Duyurular', 'Takvim etkinlikleri', 'Denemeler / Tanıma Merkezi', 'Güvenlik ve erişim']) await expect(menuGroup(page).getByRole('button', { name: n })).toBeVisible()

    await menuGroup(page).getByRole('button', { name: 'Güvenlik ve erişim' }).click()
    await expect(page.getByRole('region', { name: 'Kim neyi görür' })).toContainText('Yalnız atandığı sınıfların')
    await expect(page.getByText(/SQL düzenleyici/)).toBeVisible()
    await axe(page, 'güvenlik')
    await menuGroup(page).getByRole('button', { name: 'Mesajlaşma' }).click()
    await expect(page.getByRole('switch', { name: /Mesajlara dosya eklenebilir/ })).toHaveAttribute('aria-checked', 'true')
    await axe(page, 'mesajlaşma')
  })

  test('sınıf pasif yapılınca onay ister, kayıt formundan kalkar; geri açılır', async ({ page, browser }) => {
    await loginAdmin(page, secret)
    await page.goto('/yonetim')
    const row = page.getByTestId('class-row').filter({ hasText: '6/A' })
    await page.getByRole('button', { name: '6/A sınıfını pasif yap' }).click()
    const dlg = page.getByRole('dialog', { name: '6/A sınıfını pasif yap' })
    await expect(dlg).toContainText('silinmez')
    await dlg.getByRole('button', { name: 'Pasif yap' }).click()
    await expect(row).toContainText('Pasif')

    const anon = await (await browser.newContext()).newPage()
    await anon.goto('/')
    await anon.getByRole('button', { name: 'Kayıt ol' }).click()
    await expect(anon.getByLabel('Sınıfın').locator('option', { hasText: '6/A' })).toHaveCount(0)
    await expect(anon.getByLabel('Sınıfın').locator('option', { hasText: '8/C' })).toHaveCount(1)

    await page.getByRole('button', { name: '6/A sınıfını aktif yap' }).click()
    await page.getByRole('dialog', { name: '6/A sınıfını aktif yap' }).getByRole('button', { name: 'Aktif yap' }).click()
    await expect(row).toContainText('Aktif')
    const { data: log } = await svc.from('audit_log').select('action').eq('entity', 'classes').order('id', { ascending: false }).limit(2)
    expect(log!.map((l) => l.action)).toEqual(['update', 'update'])
  })

  test('öğrenci arşivlenir (kayıtlar silinmez) ve geri alınır', async ({ page }) => {
    const { data: c6 } = await svc.from('classes').select('id, school_id').eq('name', '6/A').single()
    await svc.from('students').insert({ full_name: STU, class_id: c6!.id, school_id: c6!.school_id })
    await loginAdmin(page, secret)
    await page.goto('/yonetim?sekme=ogrenciler')
    await page.getByRole('button', { name: `${STU} arşivle` }).click()
    const dlg = page.getByRole('dialog', { name: 'Öğrenciyi arşivle' })
    await expect(dlg).toContainText('Hiçbir kayıt silinmez')
    await dlg.getByRole('button', { name: 'Arşivle' }).click()
    await expect(page.getByTestId('student-row').filter({ hasText: STU })).toHaveCount(0)
    await page.getByRole('button', { name: /^Arşiv \(/ }).click()
    await expect(page.getByTestId('student-row').filter({ hasText: STU })).toHaveCount(1)
    await axe(page, 'öğrenci arşivi')
    await page.getByRole('button', { name: `${STU} arşivden çıkar` }).click()
    await page.getByRole('dialog', { name: 'Öğrenciyi arşivden çıkar' }).getByRole('button', { name: 'Geri al' }).click()
    await expect(page.getByTestId('student-row').filter({ hasText: STU })).toHaveCount(0)
    await page.getByRole('button', { name: /^Aktif \(/ }).click()
    await expect(page.getByTestId('student-row').filter({ hasText: STU })).toHaveCount(1)
    const { data: s } = await svc.from('students').select('archived_at').eq('full_name', STU).single()
    expect(s!.archived_at).toBeNull()
  })

  test('öğretmen penceresinden ders ataması ekle / kaldır (onaylı); atamalar ekranında kaldırma onayı', async ({ page }) => {
    await loginAdmin(page, secret)
    await page.goto('/yonetim?sekme=ogretmenler')
    await page.getByRole('button', { name: 'Esra Demir düzenle' }).click()
    const ed = page.getByRole('dialog', { name: /bilgilerini düzenle/ })
    const box = ed.getByRole('region', { name: 'Ders atamaları' })
    await box.getByLabel('Sınıf').selectOption({ label: '8/C' })
    await box.getByLabel('Ders').selectOption({ label: 'Fen Bilimleri' })
    await box.getByRole('button', { name: 'Ata', exact: true }).click()
    const chip = box.getByTestId('teacher-assignment').filter({ hasText: '8/C · Fen Bilimleri' })
    await expect(chip).toHaveCount(1)
    await axe(page, 'öğretmen ataması')
    await chip.getByRole('button', { name: /atamasını kaldır/ }).click()
    await chip.getByRole('button', { name: 'Vazgeç' }).click()
    await expect(chip).toHaveCount(1)
    await ed.getByRole('button', { name: 'Vazgeç' }).click()

    await page.goto('/yonetim?sekme=atamalar')
    await page.getByLabel('Sınıf').selectOption({ label: '8/C' })
    const row = page.getByTestId('assignment-row').filter({ hasText: 'Esra Demir' })
    await row.getByRole('button', { name: /atamasını kaldır/ }).click()
    const dlg = page.getByRole('dialog', { name: 'Ders atamasını kaldır' })
    await expect(dlg).toContainText('8/C · Fen Bilimleri')
    await dlg.getByRole('button', { name: 'Kaldır' }).click()
    await expect(row).toHaveCount(0)
  })

  test('"Öğretmenler ödev verebilir" kapalıyken öğretmenin düğmesi kapanır', async ({ page }) => {
    await loginAdmin(page, secret)
    await page.goto('/yonetim?sekme=odev')
    await page.getByRole('switch', { name: /Öğretmenler ödev verebilir/ }).click()
    await expect(page.getByRole('switch', { name: /Öğretmenler ödev verebilir/ })).toHaveAttribute('aria-checked', 'false')
    await logout(page)
    await login(page, ...DEMO.matematik)
    await page.getByRole('link', { name: 'Ödevler', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Ödev ver' })).toBeDisabled()
    await expect(page.getByText('ödev vermesini şimdilik kapattı')).toBeVisible()
    await logout(page)
    await loginAdmin(page, secret)
    await page.goto('/yonetim?sekme=odev')
    await page.getByRole('switch', { name: /Öğretmenler ödev verebilir/ }).click()
    await expect(page.getByRole('switch', { name: /Öğretmenler ödev verebilir/ })).toHaveAttribute('aria-checked', 'true')
  })

  test('yönetici Bugün kartlarını düzenler; veli kartı geniş yapılır', async ({ page }) => {
    await loginAdmin(page, secret)
    await page.goto('/bugun')
    await expect(page.locator('summary', { hasText: 'Görevler' })).toHaveCount(1)
    await page.goto('/yonetim?sekme=anasayfa')
    await page.getByRole('group', { name: 'Kimin ana sayfası' }).getByRole('button', { name: 'Yönetim (Bugün)' }).click()
    const box = page.getByRole('region', { name: 'Yönetim (Bugün) ana sayfa kartları' })
    await box.getByRole('checkbox', { name: 'Görevler' }).uncheck()
    await box.getByRole('button', { name: 'Görüşmeler yukarı' }).click()
    await expect(box.getByRole('combobox')).toHaveCount(0) // Bugün yan sütununda genişlik yok
    await page.getByRole('button', { name: 'Kaydet' }).click()
    await expect(page.getByText('Ana sayfa düzeni kaydedildi')).toBeVisible()
    await page.goto('/bugun')
    await expect(page.locator('summary', { hasText: 'Görüşmeler' })).toBeVisible()
    await expect(page.locator('summary', { hasText: 'Görevler' })).toHaveCount(0)

    await page.goto('/yonetim?sekme=anasayfa')
    const veli = page.getByRole('region', { name: 'Veli ana sayfa kartları' })
    await veli.getByLabel('Ödevler genişliği').selectOption('genis')
    await page.getByRole('button', { name: 'Kaydet' }).click()
    await expect(page.getByText('Ana sayfa düzeni kaydedildi')).toBeVisible()
    await axe(page, 'ana sayfa düzeni genişlik')
    const { data } = await svc.from('school_settings').select('value').eq('key', 'panel.veli').single()
    expect((data!.value as { id: string; w?: string }[]).find((x) => x.id === 'odev')?.w).toBe('genis')
    await logout(page)
    await login(page, ...DEMO.veli)
    await expect(page.getByRole('navigation', { name: 'Ana menü' })).toBeVisible()
    const kid = page.getByRole('group', { name: 'Öğrenciler' })
    if (await kid.isVisible().catch(() => false)) await kid.getByRole('button').first().click()
    await expect(page.locator('section[data-card="odev"]')).toHaveClass(/wide/)
    await expect(page.locator('section[data-card="duyuru"]')).not.toHaveClass(/wide/)
  })

  test('duyuru listesi: silme onay ister ve işlem geçmişine yazılır', async ({ page }) => {
    const { data: school } = await svc.from('schools').select('id').single()
    await svc.from('announcements').insert({ school_id: school!.id, title: ANN, body: 'Deneme', scope: 'okul' })
    await loginAdmin(page, secret)
    await page.goto('/yonetim?sekme=duyurular')
    await page.getByRole('button', { name: `${ANN} duyurusunu sil` }).click()
    await page.getByRole('dialog', { name: 'Duyuruyu sil' }).getByRole('button', { name: 'Sil' }).click()
    await expect(page.getByTestId('ann-row').filter({ hasText: ANN })).toHaveCount(0)
    const { data: log } = await svc.from('audit_log').select('action').eq('entity', 'announcements').order('id', { ascending: false }).limit(1).single()
    expect(log!.action).toBe('delete')
  })

  test('mobil: Yönetim Merkezi yatay taşmaz', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 })
    await loginAdmin(page, secret)
    await page.goto('/yonetim?sekme=ogrenciler')
    await expect(page.getByLabel('Yönetimde ara')).toBeVisible()
    const over = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)
    expect(over).toBeLessThanOrEqual(1)
  })
})
